version: '3'
services:
  www:
    privileged: true
    build: .
    ports:
      - 80:80
      - 443:443
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./:/var/www/
      - ./public/:/var/www/html:cached
      - ./site-enabled:/etc/apache2/sites-enabled
      - ./docker/log:/var/logscd..
      - ./docker/ssl:/etc/apache2/ssl
    networks:
      - net
  mysql:
    platform: linux/x86_64
    image: mysql:5.6
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
    volumes:
      - ./docker/data:/var/lib/mysql
    networks:
      - net
    command: mysqld --default-authentication-plugin=mysql_native_password
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 6000M
    ports:
      - 8080:80
    networks:
      - net
networks:
  net:
    driver: bridge